# Generated by Django 5.0.3 on 2024-03-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargestation',
            name='type_image',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
