# Generated by Django 5.0.3 on 2024-03-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_chargestation_type_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargestation',
            name='type_image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
