# Generated by Django 5.0.3 on 2024-03-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_chargestation_type_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
