# Generated by Django 5.0.3 on 2024-03-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_spot_is_active_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='is_electric',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
