# Generated by Django 5.0.3 on 2024-03-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_parkinghistory_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinghistory',
            name='is_parking',
            field=models.BooleanField(default=True),
        ),
    ]
