# Generated by Django 5.0.3 on 2024-03-14 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='ParkingLot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_spaces', to='app.parkinglot'),
        ),
    ]
