# Generated by Django 5.0.3 on 2024-03-20 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_role_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricvehicleinfo',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='electric_info', to='app.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='is_electric',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='app.user'),
        ),
    ]
