# Generated by Django 5.0.3 on 2024-03-21 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_parkinghistory_parking_spot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='total_space',
        ),
    ]
