# Generated by Django 5.0.3 on 2024-03-25 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_parkinglot_total_space'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
