# Generated by Django 5.0.3 on 2024-04-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='position',
            field=models.CharField(default='0,0,0', max_length=100),
        ),
    ]
