# Generated by Django 5.0.3 on 2024-04-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_parkinglot_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='is_charge',
            field=models.BooleanField(default=False),
        ),
    ]
