# Generated by Django 5.0.3 on 2024-04-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_spot_is_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='direction',
            field=models.FloatField(),
        ),
    ]
