# Generated by Django 5.0.3 on 2024-05-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_spot_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(default='#ffffff', max_length=100),
        ),
    ]
